apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: r16a-cloud-client
  namespace: r16a-cloud
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - cloud.r16a.cloud
      secretName: r16a-cloud-tls
  rules:
    - host: cloud.r16a.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: r16a-cloud-client
                port:
                  number: 80
