apiVersion: v1
kind: Service
metadata:
  name: r16a-cloud-client
  namespace: r16a-cloud
spec:
  type: ClusterIP
  selector:
    app: r16a-cloud-client
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
